all_servers:
  vars:
    ansible_ssh_user: ec2-user
    has_internet_access: true
    is_server: true

  children:
    web_servers:
      hosts:
        dns_web1_west: {}
        dns_web2_west: {}
    databases:
      hosts:
        dns_db_west: {}