- name: provision web servers for dns workshop
  hosts: web_servers
  become: true
  gather_facts: no

  vars_files:
    - 'vars/web_server.yml'

  vars:
    install_docker: true

  tasks:
    - name: Change urllib3 version for compatibility
      tags: [urllib3]
      block:
        - name: uninstall urllib3 v2.0
          pip:
            name: urllib3
            state: absent

        - name: install urllib3 >v2.0
          pip:
            name: urllib3
            version: <2.0
            state: present

    - name: configure docker
      when: install_docker
      tags: [docker]
      block:
        - name: install docker
          yum:
            name: docker
            state: present

        - name: start docker
          service:
            name: docker
            state: started

        - name: install docker SDK
          pip:
            name: docker
            state: present

    - name: install web-server
      tags: [web-server]
      docker_container:
        name: "{{ inventory_hostname }}"
        image: "benpiper/r53-ec2-web"
        state: started
        detach: yes
        auto_remove: true
        pull: yes  # Ensures the latest version is pulled
        ports:
          - "80:80"